name: Terraform CI

on:
  pull_request:
    branches:
      - main

    paths:
      - 'environments/**'
      - 'modules/**'

permissions:
  pull-requests: write
  contents: read
  id-token: write

env:
  AWS_REGION: us-west-2
  TF_VERSION: 1.9.5

jobs:

  detect-changes:
    runs-on: self-hosted

    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      test: ${{ steps.filter.outputs.test }}
      prod: ${{ steps.filter.outputs.prod }}

    steps:

      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dev:
              - 'environments/dev/**'

            test:
              - 'environments/test/**'

            prod:
              - 'environments/prod/**'

  terraform-plan:
    needs: detect-changes

    strategy:
      fail-fast: false

      matrix:
        environment:
          - dev
          - test
          - prod

    if: |
      needs.detect-changes.outputs[matrix.environment] == 'true'

    runs-on: self-hosted

    environment:
      name: ${{ matrix.environment }}

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ matrix.environment }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -lock=true \
            -lock-timeout=300s \
            -no-color \
            -out=tfplan > plan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: |
            environments/${{ matrix.environment }}/tfplan
            environments/${{ matrix.environment }}/plan.txt

      - name: Comment Terraform Plan
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/plan.txt